# Introduction

### Exercice 1

In [18]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [15]:
a = [1,2,3]
b = [4,5,6]

In [16]:
lstA = np.array(a)
lstB = np.array(b)  

print("somme de a+b : ",lstA+lstB)
print("soustraction de a-b :",lstA-lstB)

somme de a+b :  [5 7 9]
soustraction de a-b : [-3 -3 -3]


In [17]:
lstA = np.append(lstA,10)
print(lstA)
lstB = np.append(lstB,10)
print(lstB)

[ 1  2  3 10]
[ 4  5  6 10]


In [20]:
lstA == lstB

array([False, False, False,  True])

In [29]:
print(np.concatenate([lstA,lstB]))

[ 1  2  3 10  4  5  6 10]


In [35]:
lstC = np.array([-10,10])

In [ ]:
x = np.arange([lstC])
y =x^2 